### ISSUE TITLE
issue in transforms_utils.py

### ISSUE THREAD

**Issue by sparshgarg23** [johnwlambert/argoverse_cbgs_kf_tracker#2]
Hi,I was running the transforms_utils.py 
During execution of the function test_yaw_to_quaternion3d(),it seems that the quaternion values computed by yaw_2_quaternion3d() have opposite signs (this starts at iteration 26)
For eg:
at iteration 27,Rotation.from_dcm(dcm).as_quat() has the following quaternion values
0.0 0.0 0.5183925683105252 -0.8551427630053461
whereas the function yaw_2_quaternion3d() prints the following values
0.0 0.0 -0.5183925683105252 0.855142763005346
Another example where the signs are switched for z and w 
at iteration 41
Any ideas why the signs are being switched?I feel that the switching in signs may have a significant effect on tracking later on as

**Comment by johnwlambert** [comment]
I never got around to answering this, but a unit quaternion multiplied by -1 yields an identical 3d rotation matrix:

https://math.stackexchange.com/questions/2016282/negative-quaternion
https://math.stackexchange.com/questions/1790521/unit-quaternion-multiplied-by-1
