### ISSUE TITLE
Detection performances

### ISSUE THREAD

**Issue by zhangpur** [johnwlambert/argoverse_cbgs_kf_tracker#5]
Hi, thanks for sharing the code. How can I know the detection performances?

**Comment by johnwlambert** [comment]
Hi @zhangpur, thanks for your interest in my work.

This repo just introduces a tracker on pre-computed detections. The detections are available here: https://github.com/johnwlambert/argoverse_cbgs_kf_tracker#precomputed-3d-detections

The performance of the detector can be determined by uploading the detection [zip file](https://s3.amazonaws.com/argoai-argoverse/detections_v1.1b.zip) to the Argoverse 1.1 Detection Leaderboard on EvalAI.

Leaderboard: https://eval.ai/web/challenges/challenge-page/725/overview

From what I call, the Average Composite Detection Score (AVG-CDS) of that baseline is shown on the [leaderboard](https://eval.ai/web/challenges/challenge-page/725/leaderboard/1974): **Host_89109_Team (Argoverse Detection Baseline)** with 0.35 AVG-CDS, but you could also confirm that yourself by uploading that zip file to the Argoverse Detection leaderboard.

Let me know if you have any further questions.

**Comment by zhangpur** [comment]
Thanks for your reply :).
